<?php $notes = $this->notes;?>
<div class='container' >
          <div class="row">
                 <div id='giaiphap-ez1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['product6']['title'];?></div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh ">
                                   <?php echo $notes['product6']['description'];?>  
                                  </p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-product" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                               <div class="col-md-7 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/IMAC.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="width: 95%; max-width: 524px; margin-bottom: 1%;height: 435px;margin-top: 3%;">
                                     
                              </div>
                              
                              
                                 <div class="col-md-5 pagination-centered" style="margin-left: 0;">
								  
                                  <h3 class="col-md-12 text-left" style="margin-left: 2.564102564102564%;"><i><img src="<?php echo WEB_PATH;?>/public/front/img/GesTion_de_re.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product7']['title'];?></h3>
                                    <p class="text-just col-md-12">
                                     <?php echo $notes['product7']['description'];?> 
                                    </p>
          
                                  <h3 class="col-md-12 text-left"><i><img src="<?php echo WEB_PATH;?>/public/front/img/Gestion_de_client.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product8']['title'];?></h3>
                                    <p class="text-just col-md-12">
                                     <?php echo $notes['product8']['description'];?> 
                                     </p>

                               </div>
                                
                           

                          </div><!-- class="item active row" -->
                           <div class="item   row item-doc1 hieght-pad"></div>
                           <div class="item   row item-doc1 hieght-pad"></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->

<div class="next"><a href="<?php echo WEB_PATH;?>/front/product/product4">next</a></div>
<?php die();?>