<?php $notes = $this->notes; ?>
<div class="report-bc">
<div class='container' >
          <div class="row">
                 <div id='maket-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang-product'><?php echo $notes['marketing']['title'];?> </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh-product ">
                                  <?php echo $notes['marketing']['description'];?>
                                  </p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="box-market" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-procd ">
                                 
                                  <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                   
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/marketing-01.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="width: 100%; height: 100%;">
                                      
                                </div>
                                 
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
	                                   <h3 class="col-md-12 text-left-prod" style="margin-left: 2.564102564102564%;"><i><img src="<?php echo WEB_PATH;?>/public/front/img/email_mark.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product13']['title'];?></h3>
									   <p class="text-just-prod col-md-12">
									   <?php echo $notes['product13']['description'];?>
									   </p>
									  
                                  </div>
                                 

                          </div><!-- class="item active row" -->
                          
                          <div class="item  active row item-procd ">
                           	   <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                  <h3 class="col-md-12 text-left-prod" style="margin-left: 2.564102564102564%;"><i><img src="<?php echo WEB_PATH;?>/public/front/img/the_k_hang.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product14']['title'];?></h3>
								   <p class="text-just-prod col-md-12">
                                              <?php echo $notes['product14']['description'];?>
								   </p>
                                  </div>
                                
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                 
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/marketing-02.png" alt="caisse enregistreuse caltos"  class="col-md-12" >
                                     
                                </div>
                                
                           </div><!--  class="item   row item-procd " -->
                           
                           
                           <div class="item active  row item-procd ">
                           
                           	 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                   
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/marketing-03.png" alt="caisse enregistreuse caltos"  class="col-md-12" >
                                      
                             </div>
                                
                           	 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                  <h3 class="col-md-12 text-left-prod" style="margin-left: 2.564102564102564%;"><i><img src="<?php echo WEB_PATH;?>/public/front/img/the_tra-truoc.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product15']['title'];?> </h3>
								   <p class="text-just-prod col-md-12">
								   <?php echo $notes['product15']['description'];?>
								    </p>
                             </div>
                                
                                
                           
                           </div><!--  class="item   row item-procd " -->

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
  </div><!-- class='container' id="giaiphap-ez2" -->
</div><!-- report-bc -->
<?php die();?>                                     