<?php $notes = $this->notes; ?>
<div class="report-bc">
<div class='container' >
          <div class="row">
                 <div id='quanlycuahang-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['product12']['title'];?></div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id='_contect_khachhang'>
                                  <p class="p-view-ttkh ">
                                 
                                  </p>
                                </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="quanlycuahang-prod-ez2" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-page5 ">
                                 
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                   <p class="text-just col-md-12"></p>
								   <p class="text-just col-md-12">
                                     <?php echo $notes['product12']['description'];?>  
                                   </p>
          						
          							 <div class="col-md-1"></div>
                                     <div  class="col-md-10"><h3 class="baocao-product">M'Inscrire</h3></div>
                                     <div  class="col-md-1" ></div>
                                     
                                </div>
                                
                                 <div class="col-md-6 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/image_baocao.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="width: 95%; max-width: 489px; margin-bottom: 1%;height: 386px;">
                                     
                                </div>
                                
                           

                          </div><!-- class="item active row" -->
                           <div class="item   row item-page5 "></div>
                           <div class="item   row item-page5 "></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
  </div><!-- class='container' id="giaiphap-ez2" -->
</div><!-- report-bc -->

<div class="next"><a href="<?php echo WEB_PATH;?>/front/product/product6">next</a></div>
<?php die();?>