<?php $notes = $this->notes; ?>
<div class='container tn-prod-2' >

	<div class="row">
	 <!--  
		 <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 tinhnang-text'></div>
	 	 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h3 class='tinhnang-text-h3'>Ventes sur tous les équipements</h3>
          <p class='tinhnang-text-p'></p>                
         </div>
      -->                    
	</div><!-- class="row" -->

	  
	 	 <div class='row  '>
                   <div class="article-tinhnang">

<div class="action-layer" data-stellar-background-ratio="0.5" data-stellar-vertical-offset="100" style="background-position: 0% -46.5px;"></div>  

                              <section id="features" class="container">     
                                  <!-- Featured Section Calls to Action -->
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 ez-hotro-box item animate_afc d1 animate_start">
                                      
                                      <article class="ez2-block">
                                        <div class="caption-prod"> 
                                          <h3 class='ez-box'><i><img src="<?php echo WEB_PATH;?>/public/front/img/Creances.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product9']['title'];?></h3>
                                          <p class="ez-box-pro-pro">
                                          <?php echo $notes['product9']['description'];?>  
										  </p>
                                        </div>
                                      </article>

                                    </div>

                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d2 animate_start">
                                     
                                      <article class="ez2-block">
                                        
                                        <div class="caption-prod">  
                                          <h3 class='ez-box'><i><img src="<?php echo WEB_PATH;?>/public/front/img/Gestion.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product10']['title'];?></h3>
                                          <p class="ez-box-pro-pro">
                                          <?php echo $notes['product10']['description'];?>  
                                           </p>
                                        </div>
                                      </article>

                                    </div>

                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12  ez-hotro-box item animate_afc d3 animate_start">
                                    
                                      <article class="ez2-block">
                                        
                                        <div class="caption-prod">  
                                          <h3 class='ez-box'><i><img src="<?php echo WEB_PATH;?>/public/front/img/Chaine.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product11']['title'];?></h3>
                                          <p class="ez-box-pro-pro">
                                           <?php echo $notes['product11']['description'];?>
                                          </p>
                                         
                                        </div>
                                      </article>

                                    </div>


                                  </div><!-- class="row" -->
                                  <!-- End Featured Section Calls to Action -->
                                </section>

                      </div><!-- class="article-tinhnang" -->
                        
	 </div><!-- class="row" -->


</div><!-- container-->
<div class="next"><a href="<?php echo WEB_PATH;?>/front/product/product5">next</a></div>
<?php die();?>