<!DOCTYPE html>
<html>
  <head>
   <title>SevenMag - Just another WordPress site</title>
	<meta charset="UTF-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<link rel="pingback" href="hsevenmag/xmlrpc.php" />

	<link rel="alternate" type="application/rss+xml" title="SevenMag &raquo; Feed" href="hsevenmag/?feed=rss2" />
<link rel="alternate" type="application/rss+xml" title="SevenMag &raquo; Comments Feed" href="hsevenmag/?feed=comments-rss2" />
<link rel="alternate" type="application/rss+xml" title="SevenMag &raquo; Home Comments Feed" href="hsevenmag/?feed=rss2&#038;page_id=39" />
<link rel='stylesheet' id='al-style-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-ajax-login/style.css?ver=1.0' type='text/css' media='all' />
<link rel='stylesheet' id='arqam-style-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/arqam/assets/style.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='bbp-default-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/bbpress/templates/default/css/bbpress.css?ver=2.5.3-5249' type='text/css' media='screen' />
<link rel='stylesheet' id='contact-form-7-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=3.7.2' type='text/css' media='all' />
<link rel='stylesheet' id='symple_shortcode_styles-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/symple-shortcodes/includes/css/symple_shortcodes_styles.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='wp-polls-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-polls/polls-css.css?ver=2.63' type='text/css' media='all' />
<link rel='stylesheet' id='sevenstyle-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/style.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='icons-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/styles/icons.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='animate-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/styles/animate.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='responsive-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/styles/responsive.css?ver=3.8.1' type='text/css' media='all' />
<link rel='stylesheet' id='customizercss-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/customizer/style.css?ver=3.8.1' type='text/css' media='all' />
<script type='text/javascript' src='http://www.google.com/recaptcha/api/js/recaptcha_ajax.js?ver=1.0'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-includes/js/jquery/jquery.js?ver=1.10.2'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-ajax-login/js/jquery.blockUI.js?ver=2.53'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var ajaxwp_loginl_data = {"ajaxurl":"http:\/\/theme20.com\/sevenmag\/wp-admin\/admin-ajax.php","loadingurl":"http:\/\/theme20.com\/sevenmag\/wp-content\/plugins\/wp-ajax-login\/img\/ajax-loader.gif","public_key":"6LfW4e8SAAAAALsG-M_urX5WfqaDJhkYaCprQ8ae","captcha_enter":"Enter the two words above","captcha_get":"Get another Captcha"};
/* ]]> */
</script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-ajax-login/js/ajax-login.js?ver=2.0'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-includes/js/comment-reply.min.js?ver=3.8.1'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="<?php echo WEB_PATH;?>/public/hsevenmag/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="<?php echo WEB_PATH;?>/public/hsevenmag/wp-includes/wlwmanifest.xml" /> 
<link rel='prev' title='Fullwide' href='<?php echo WEB_PATH;?>/public/hsevenmag/?page_id=2' />
<link rel='next' title='Shortcodes' href='<?php echo WEB_PATH;?>/public/hsevenmag/?page_id=142' />
<meta name="generator" content="WordPress 3.8.1" />
<link rel='canonical' href='<?php echo WEB_PATH;?>/public/hsevenmag/' />
<link rel='shortlink' href='<?php echo WEB_PATH;?>/public/hsevenmag/?p=39' />
<style type="text/css">
.wp-polls .pollbar {
	margin: 1px;
	font-size: 6px;
	line-height: 8px;
	height: 8px;
	background-image: url('<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-polls/images/default/pollbg.gif');
	border: 1px solid #c8c8c8;
}
</style>
<!--[if IE 7]>
<link rel="stylesheet" href="hsevenmag/wp-content/plugins/wp-review/assets/css/wp-review-ie7.css">
<![endif]-->
<meta name="description" content="Home">
<meta name="keywords" content="blog,review,magazine,ad,game,theme,wordpress,themeforest,theme20" />
<link rel="shortcut icon" href="<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/uploads/2014/03/favicon.png" />
<link rel="apple-touch-icon" href="<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/uploads/2014/03/apple-touch-icon.png">
<meta name="generator" content="Powered by Visual Composer - drag and drop page builder for WordPress."/>
<style type="text/css">
				.percentage-point .review-result { background-color: #333333; }

						.review-wrapper, .review-title, .review-desc p{ color: ;}
			.review-list li, .review-wrapper{ background: ;}
			.review-title, .review-list li:nth-child(2n){background: ;}

			.bar-point .allowed-to-rate .review-result, .percentage-point .allowed-to-rate .review-result{background: none;}
			.review-total-star.allowed-to-rate a i { color: #333333; opacity: 0.50; filter: alpha(opacity=50); }
			.bar-point .allowed-to-rate .review-result, .percentage-point .allowed-to-rate .review-result{text-indent:0;}
			.bar-point .allowed-to-rate .review-result i, .percentage-point .allowed-to-rate .review-result i, .mts-user-review-star-container .selected i { color: #333333; opacity: 1; filter: alpha(opacity=100); }
			.review-wrapper, .review-title, .review-list li, .review-list li:last-child, .user-review-area{border-color: ;}
							.user-review-area{border: 1px solid ; margin-top: 0px;}
				.review-desc{width: 100%;}
				.review-wrapper{border: none; overflow: visible;}
			</style><style type="text/css">
body{background-image:url(<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/uploads/2014/03/BlurredBackground9.jpg);background-repeat:repeat;background-attachment:fixed;background-position:center top;background-color:#ddd;background-size:auto;}
.featured_thumb .thumb-icon {background: rgba(0,0,0, 0.4);}
</style>

	<!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=EmulateIE8; IE=EDGE" />
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
    <!end headeer-->
  </head>
  <body class='contrast-blue '>
      <div id="layout" class="boxed-margin">
          
      </div>
    
    
    
    
     <!-- / jquery [required] -->
    <link rel='stylesheet' id='js_composer_front-css'  href='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/js_composer/assets/css/js_composer_front.css?ver=4.0.2' type='text/css' media='all' />
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/bbpress/templates/default/js/editor.js?ver=2.5.3-5249'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?ver=3.50.0-2014.02.05'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/theme20.com\/sevenmag\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ..."};
/* ]]> */
</script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=3.7.2'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var pollsL10n = {"ajax_url":"http:\/\/theme20.com\/sevenmag\/wp-admin\/admin-ajax.php","text_wait":"Your last request is still being processed. Please wait a while ...","text_valid":"Please choose a valid poll answer.","text_multiple":"Maximum number of choices allowed: ","show_loading":"1","show_fading":"1"};
/* ]]> */
</script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/wp-polls/polls-js.js?ver=2.63'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/js/owl.carousel.min.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/js/jquery.li-scroller.1.0.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/js/seven.min.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/js/jquery.fitvids.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/js/custom.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/themes/sevenmag/customizer/script.js?ver=3.8.1'></script>
<script type='text/javascript' src='<?php echo WEB_PATH;?>/public/hsevenmag/wp-content/plugins/js_composer/assets/js/js_composer_front.js?ver=4.0.2'></script>

   
  </body>
</html>