<footer id="footer">

    <div class="row clearfix">
        <div class="alpha grid_3 footer_w">
            <div id="t20_posts-2" class="widget_T20_posts">
                <div class="b_title"><h4>Popular from Movies</h4></div><div class="widget clearfix">

                    <div class="more_posts">
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=23" title="Should creatives be unionized or earn">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/03/photo-12-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="Pretty Girl" />
                                        <span class="thumb-icon"><i class="icon-camera"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=23" rel="bookmark" title="Should creatives be unionized or earn">Should creatives be unionized or earn</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=23"><i class="icon-calendar mi"></i>4 Jan, 2014</a>
                                        <a href="hsevenmag/?p=23#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="23 hsevenmag/?p=23">3</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=120" title="Big brand theory: packaging design">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/02/311-entete-fotolia_51161496_m-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="Bike" />
                                        <span class="thumb-icon"><i class="icon-export"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=120" rel="bookmark" title="Big brand theory: packaging design">Big brand theory: packaging design</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=120"><i class="icon-calendar mi"></i>11 Feb, 2014</a>
                                        <a href="hsevenmag/?p=120#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="120 hsevenmag/?p=120">2</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=60" title="Mobile first: Luke Wroblewski interview">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/03/davy_jones-wallpaper-1920x1440-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="davy_jones-wallpaper-1920x1440" />
                                        <span class="thumb-icon"><i class="icon-export"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=60" rel="bookmark" title="Mobile first: Luke Wroblewski interview">Mobile first: Luke Wroblewski interview</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=60"><i class="icon-calendar mi"></i>10 Jan, 2014</a>
                                        <a href="hsevenmag/?p=60#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="60 hsevenmag/?p=60">2</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=1" title="Hello world!">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/03/photodune-524369-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="Sunset" />
                                        <span class="thumb-icon"><i class="icon-export"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=1" rel="bookmark" title="Hello world!">Hello world!</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=1"><i class="icon-calendar mi"></i>1 Jan, 2014</a>
                                        <a href="hsevenmag/?p=1#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="1 hsevenmag/?p=1">1</span></a>						</div>
                                </div>
                            </div>
                        </div>
                    </div><!--/.T20-posts-->

                </div></div><!-- .widget /-->
        </div>
        <div class="grid_3 footer_w">
            <div id="t20_posts-3" class="widget_T20_posts">
                <div class="b_title"><h4>Random Posts</h4></div><div class="widget clearfix">

                    <div class="more_posts">
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=54" title="How web posture affects experience">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/03/shutterstock_144233608-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="Music Video Cover" />
                                        <span class="thumb-icon"><i class="icon-media-play"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=54" rel="bookmark" title="How web posture affects experience">How web posture affects experience</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=54"><i class="icon-calendar mi"></i>9 Jan, 2014</a>
                                        <a href="hsevenmag/?p=54#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="54 hsevenmag/?p=54">0</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=83" title="A fresh approach to iStock">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/03/shutterstock_100179557-3-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="" />
                                        <span class="thumb-icon"><i class="icon-camera"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=83" rel="bookmark" title="A fresh approach to iStock">A fresh approach to iStock</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=83"><i class="icon-calendar mi"></i>7 Feb, 2014</a>
                                        <a href="hsevenmag/?p=83#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="83 hsevenmag/?p=83">0</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=75" title="BIG GAME">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/02/53955593_Subscription_L-2-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="beautiful model with fashion make-up" />
                                        <span class="thumb-icon"><i class="icon-media-play"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=75" rel="bookmark" title="BIG GAME">BIG GAME</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=75"><i class="icon-calendar mi"></i>6 Feb, 2014</a>
                                        <a href="hsevenmag/?p=75#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="75 hsevenmag/?p=75">0</span></a>						</div>
                                </div>
                            </div>
                        </div>
                        <div class="item_small">
                            <div class="one_post">
                                <div class="featured_thumb">
                                    <a href="hsevenmag/?p=88" title="Beautiful lettering of yesteryear">
                                        <img width="80" height="80" src="hsevenmag/wp-content/uploads/2014/02/Brazil-football-fans-1928611-80x80.jpg" class="attachment-thumbnail wp-post-image" alt="Brazil-football-fans-1928611" />
                                        <span class="thumb-icon"><i class="icon-export"></i></span>								</a>
                                </div>
                                <div class="item-details">
                                    <h3><a href="hsevenmag/?p=88" rel="bookmark" title="Beautiful lettering of yesteryear">Beautiful lettering of yesteryear</a></h3>
                                    <div class="post_meta">
                                        <a href="hsevenmag/?p=88"><i class="icon-calendar mi"></i>8 Feb, 2014</a>
                                        <a href="hsevenmag/?p=88#comments"><i class="icon-message mi"></i><span class="dsq-postid" rel="88 hsevenmag/?p=88">0</span></a>						</div>
                                </div>
                            </div>
                        </div>
                    </div><!--/.T20-posts-->

                </div></div><!-- .widget /-->
        </div>
        <div class="grid_3 footer_w">
            <div id="t20_posts_slideshow-2" class="widget_T20_posts_slideshow">
                <div class="b_title"><h4>Slideshow</h4></div><div class="widget clearfix">

                    <div class="gallery_widget gallery_widget_posts owl-carousel owl-theme">

                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=88" title="Beautiful lettering of yesteryear" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/02/Brazil-football-fans-1928611-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="Brazil-football-fans-1928611" />							<span class="thumb-icon"><i class="icon-export"></i></span>							<h3>Beautiful lettering of yesteryear</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=88"><i class="icon-calendar mi"></i> 8 Feb, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=88#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="88 hsevenmag/?p=88">0</span></a></span>
                            </div>
                        </div>


                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=120" title="Big brand theory: packaging design" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/02/311-entete-fotolia_51161496_m-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="Bike" />							<span class="thumb-icon"><i class="icon-export"></i></span>							<h3>Big brand theory: packaging design</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=120"><i class="icon-calendar mi"></i> 11 Feb, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=120#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="120 hsevenmag/?p=120">2</span></a></span>
                            </div>
                        </div>


                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=124" title="4 essential rules of effective logo design" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/03/photodune-1333976-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="photodune-1333976" />							<span class="thumb-icon"><i class="icon-export"></i></span>							<h3>4 essential rules of effective logo design</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=124"><i class="icon-calendar mi"></i> 10 Mar, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=124#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="124 hsevenmag/?p=124">0</span></a></span>
                            </div>
                        </div>


                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=17" title="The future of the web is video" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/03/photodune-6137350-beautiful-young-blonde-hipster-woman-listening-music-m-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="beautiful young blonde hipster woman listening music" />							<span class="thumb-icon"><i class="icon-media-play"></i></span>							<h3>The future of the web is video</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=17"><i class="icon-calendar mi"></i> 3 Jan, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=17#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="17 hsevenmag/?p=17">0</span></a></span>
                            </div>
                        </div>


                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=8" title="4 essential rules of effective logo design" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/03/firestock_mail_08102013-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="At symbol with laptop" />							<span class="thumb-icon"><i class="icon-export"></i></span>							<h3>4 essential rules of effective logo design</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=8"><i class="icon-calendar mi"></i> 2 Jan, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=8#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="8 hsevenmag/?p=8">0</span></a></span>
                            </div>
                        </div>


                        <div class="item wgr T_post">
                            <div class="featured_thumb">
                                <a class="first_A" href="hsevenmag/?p=43" title="App icons with hidden messages" rel="bookmark" >
                                    <img width="255" height="280" src="hsevenmag/wp-content/uploads/2014/03/shutterstock_64104292-255x280.jpg" class="attachment-blocktwo wp-post-image" alt="Pretty Love" />							<span class="thumb-icon"><i class="icon-music"></i></span>							<h3>App icons with hidden messages</h3>
                                </a>
                            </div>
                            <div class="details">
                                <span class="s_category">
                                    <a href="hsevenmag/?p=43"><i class="icon-calendar mi"></i> 7 Jan, 2014</a>
                                    <a href="http://localhost/wordpress3/?author=1"><i class="icon-user mi"></i>admin</a>
                                </span>
                                <span class="more_meta"><a href="hsevenmag/?p=43#comments"><i class="icon-message mi"></i> <span class="dsq-postid" rel="43 hsevenmag/?p=43">0</span></a></span>
                            </div>
                        </div>

                    </div><!--/slideshow-->

                </div></div><!-- .widget /-->
        </div>
        <div class="omega grid_3 footer_w">
            <div id="t20_subscribe_feed_widget-2" class="widget_subscribe"><div class="b_title"><h4>Subscribe to RSS Feeds</h4></div><div class="widget clearfix">		<p>Get all latest content delivered to your email a few times a month. Updates and news about all categories will send to you.</p>
                    <form class="widget_rss_subscription" action="http://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=sevenpsd', 'popupwindow', 'scrollbars=yes,width=550,height=520');
                            return true">
                        <input type="text" placeholder="Your email" name="email" required />
                        <input type="hidden" value="sevenpsd" name="uri"/>
                        <input type="hidden" name="loc" value="en_US"/>
                        <button type="submit" id="submit" value="Subscribe"><span>Sign Up</span></button>
                    </form>

                </div></div><!-- .widget /--><div id="t20_social_icons_widget-2" class="widget_social"><div class="b_title"><h4>Follow Us</h4></div><div class="widget clearfix">
                    <div class="social with_color">
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Follow us on twitter"><i class="fa fa-twitter"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Like us on facebook"><i class="fa fa-facebook"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Follow us on dribbble"><i class="fa fa-dribbble"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Follow us on Google+"><i class="fa fa-google-plus"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Foursquare"><i class="fa fa-foursquare"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Follow us on Soundcloud"><i class="fa fa-cloud"></i></a>
                        <a rel="nofollow" class="toptip" href="#" target="_blank" title="Flickr"><i class="fa fa-flickr"></i></a>

                    </div>
                </div></div><!-- .widget /-->						</div>
    </div><!-- /row -->

    <div class="row clearfix">
        <div class="footer_last">
            <span class="copyright">Copyright 2014 by Theme20. All Rights Reserved. Powered by Wordpress</span>

            <nav class="nav-footer" id="nav-footer">
                <ul class="sf-menu"><li id="menu-item-129" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-39 current_page_item menu-item-129"><a href="hsevenmag/">Home</a></li>
                    <li id="menu-item-127" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-127"><a href="hsevenmag/?post_type=forum">Forums</a></li>
                    <li id="menu-item-160" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-160"><a href="hsevenmag/?cat=6">Movies</a></li>
                    <li id="menu-item-161" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-161"><a href="hsevenmag/?cat=2">Reviews</a></li>
                    <li id="menu-item-162" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-162"><a href="hsevenmag/?cat=3">Games</a></li>
                    <li id="menu-item-167" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-167"><a href="hsevenmag/?page_id=163">Contact</a></li>
                </ul>					</nav><!--/nav-footer-->
        </div><!-- /last footer -->
    </div><!-- /row -->

</footer>