<!DOCTYPE html>
<html>

    <body class='contrast-red login blue-background'>
<div id="layout" class="boxed-margin">
        <div class='middle-container' style="background-color: #00ACEC; height: 450px;">
            <div class='middle-row'>
                <div class='middle-wrapper'>
                    <div class='login-container-header' style="background-color: #00ACEC;">
                        <div class='container'>
                            <div class='row'>
                                <div class='col-sm-12'>
                                    <div class='text-center'>
                                          </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!--footer-->
                </div><!-- /layout -->
                <div id="toTop"><i class="icon-arrow-thin-up"></i></div>

                <div class="style-picker">
                    <div class="container bgChanger"> <a href="#" class="handler" title="Live Styles Customizer">&nbsp;</a> 
                        <div class="options clearfix">
                            <div class="grid_6"><span> Layout </span> 
                                <select name="layouts" id="layouts">
                                    <option value="full" class="fullval">Fullwide</option>
                                    <option value="boxed" class="boxedval">Boxed</option>
                                    <option value="boxed-margin" selected class="boxedmarginval">Boxed Margin</option>
                                </select>
                            </div>
                            <div class="grid_6"><span> Version </span> 
                                <select name="version" id="version">
                                    <option value="light" class="lightval">Light</option>
                                    <option value="dark" class="darkval">Dark</option>
                                </select>
                            </div>
                            <div id="bgs">
                                <div class="stBgs stBlock"> <span> Backgrounds </span>  
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/1.png" class="thumb-img bgBody" title="1" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/1.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/2.png" class="thumb-img bgBody" title="2" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/2.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/3.png" class="thumb-img bgBody" title="3" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/3.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/4.png" class="thumb-img bgBody" title="4" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/4.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/6.png" class="thumb-img bgBody" title="6" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/5.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/9.png" class="thumb-img bgBody" title="9" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/6.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/10.png" class="thumb-img bgBody" title="10" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/7.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/12.jpg" class="thumb-img bgBody" title="12" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/8.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/13.jpg" class="thumb-img bgBody" title="13" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/9.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/14.jpg" class="thumb-img bgBody" title="14" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/10.jpg)">&nbsp;</a>
                                    <a rel="hsevenmag/wp-content/themes/sevenmag/images/backgrounds/15.jpg" class="thumb-img bgBody" title="15" style="background: url(hsevenmag/wp-content/themes/sevenmag/customizer/images/backgrounds/2.jpg)">&nbsp;</a>
                                </div>
                            </div>
                            <div class="cl"><a href="#" class="bgColor">Color Scheme<span id="bgHeaderColor" title="FF0078" style="background-color:#FF0078">&nbsp;</span></a>
                            </div>
                            <div Class="grid_6"><span>Headings Font</span>
                                <select name="hfont" id="hfont"></select>
                            </div>
                            <div Class="grid_6 mb"><span>Content Font</span>
                                <select name="pfont" id="pfont"></select>
                            </div>

                            <p> Also have more settings in Theme Options. </p> 
                        </div>
                    </div>
                </div>
                <!--end footer-->
            </div>
        </div>
    </div>
 
</body>
</html>