<?php $notes = $this->notes; //var_dump($notes);die();?>
<header id="header" class="site-header"> 
    <section id="feature_slider" class="disabled">
        <article class="slide" id="showcasing" style="background-image: url('img/backgrounds/banner-web1911.jpg'); display: block; opacity: 0.868928; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-30 sp600 t120 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene1/macbook.png" style="left: -966px; top: 120px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Enregistrer 500 magasins après 120 jours - votre magasin sera 501?.</h2>
            </div>
        </article>
        <article class="slide active" id="ideas" style="background-image: url('img/backgrounds/giai-phap-tong-the_4.jpg');  display: block; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <div class="info" style="display: none;">
                <h2>Synchronisation du matériel</h2>
            </div>
            <img class="asset left-480 sp600 t260 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/left.png" style="left: 1086.8833777777777px; top: 260px; z-index: 1; display: inline;">
            <img class="asset left-210 sp600 t213 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/middle.png" style="left: 1189.7953777777777px; top: 213px; z-index: 2; display: inline;">
            <img class="asset left60 sp600 t260 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene2/right.png" style="left: 1292.7073777777778px; top: 260px; z-index: 1; display: inline;">
        </article>
        <article class="slide" id="tour" style="background-image: url('img/backgrounds/landscape.png');  display: none; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-472 sp650 t210 z3" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/ipad.png" style="left: -558px; top: 210px; z-index: 3; display: inline;">
            <img class="asset left-365 sp600 t270 z4" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/iphone.png" style="left: -485px; top: 270px; z-index: 4; display: inline;">
            <img class="asset left-350 sp450 t135 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/desktop.png" style="left: -742px; top: 135px; z-index: 2; display: inline;">
            <img class="asset left-185 sp550 t220 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene3/macbook.png" style="left: -746px; top: 220px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Fonctionne sur tous les appareils</h2>
                <a href="features.html">toujours à explorer</a>
            </div>
        </article>
         <article class="slide" id="showcasing" style="background-image: url('img/backgrounds/banner-web1911.jpg'); display: block; opacity: 0.868928; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-30 sp600 t120 z1" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene1/macbook.png" style="left: -966px; top: 120px; z-index: 1; display: inline;">
            <div class="info" style="display: none;">
                <h2>Maybanhang.net anniversaire.</h2>
            </div>
        </article>
        <article class="slide" id="responsive" style="background-image: url('img/backgrounds/phan-cung-dong-bo_1.jpg');  display: none; background-position: 50% 0%; background-repeat: repeat no-repeat;">
            <img class="asset left-472 sp600 t120 z3" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene4/html5.png" style="left: -732px; top: 120px; z-index: 3; display: inline;">
            <img class="asset left-190 sp500 t120 z2" src="<?php echo WEB_PATH;?>/public/front/img/slides/scene4/css3.png" style="left: -732px; top: 120px; z-index: 2; display: inline;">
            <div class="info" style="display: none;">
                <h3>
                  Technologie avancée <strong>HTML5 , CSS3,.... &amp; Cloud Computing</strong>
                </h3>                
            </div>
        </article> 
   
</section>
    <div class='container p-view'>
        <div class='row'>
            <div class='col-lg-1 col-md-1 col-sm-1 col-xs-12'></div>
            <div class='col-lg-11 col-md-11 col-sm-11 col-xs-12 text-view-product'>
               Logiciel de gestion pour les magasins, les superettes, les cafés, les restaurants…est fourni comme une prestation.
L’ensemble de POSMANAGER.FR s’oriente vraiment à la commodité, aux facilités d’utilisation et à la mobilité des utilisateurs.
            </div>
            <div class='col-lg-1 col-md-1 col-sm-1 col-xs-12'></div>
        </div>
    </div>
 </header>

  <footer id="footer" class="footer">
   
 
      <div class="container">
      <?php  /*
        <div > <!-- class="row-fluid" -->
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          
            <div class="notify-wrapper">
              <div class="notify-inner">
                <a class="notify" href="#" id='dang-ki-view'>M’INSCRIRE</a>
              </div>
            </div>
        </div>
      </div>
      */
    ?>
    </div>
 
  </footer>

     <div class="scroll" data-ui="jscroll-default">
     <div class='container' >
          <div class="row">
                 <div id='giaiphap-pag1-prod' >
                      <div class="row height-view-pro"></div>
                      <!-- col-lg-3 col-md-3 col-sm-12 col-xs-12 animate_afl d1 animate_start -->
                      <div class=" ani row animate_afl d1 animate_start ">
                            <div class="row ">
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12 giaiphap'></div>
                                <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12' id='title_khachhang'><?php echo $notes['product0']['title'];?> </div>
                               
                            </div><!-- end row -->

                      </div><!-- class="row animate_afl d1 animate_start" -->
                     


                        </div><!-- id='giaiphap' -->
                  </div> <!-- class -row-->
    </div><!-- container-->
    <div class='container' id="giaiphap-ez2" >
 
    <div class='row  '>
       <div id="content" class="container_12">
            

      <div id="home-page" class="container content">
                   <!-- Till - block -->

            <section id="till-block" class="row">


                    <div id="slider-app">

                        <div id="tillCarousel" class="carousel slide hidden-phone" data-interval="false">

                        <div class="carousel-inner col-md-12">

                          <div class="item active  row item-doc1 hieght-pad">
                               
                                 <div class="col-md-7 pagination-centered" style="margin-left: 0;">
								  
                                  <h3 class="col-md-12 text-left-product">
                                      <i>
                                      <img src="<?php echo WEB_PATH;?>/public/front/img/ventes.png" class=" iconspan6 re-tkiem">
                                      </i>
                                      <?php echo $notes['product1']['title'];?>
                                  </h3>
                                    <p class="text-just col-md-11">
                                      <?php echo $notes['product1']['description'];?> 
                                     </p>
          
                                  <h3 class="col-md-12 text-left-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/Rapports.png" class=" iconspan6 re-tkiem"></i>  <?php echo $notes['product2']['title'];?></h3>
                                    <p class="text-just col-md-11"> <?php echo $notes['product2']['description'];?>  </p>

                                 <h3 class="col-md-12 text-left-product"><i><img src="<?php echo WEB_PATH;?>/public/front/img/Gerer.png" class=" iconspan6 re-tkiem"></i><?php echo $notes['product3']['title'];?></h3>
                                    <p class="text-just col-md-11">
                                     <?php echo $notes['product3']['description'];?> 
                                    </p>
                                <h3 class='h3-span-pro'>
                                
                                <?php echo $notes['product4']['title'];?></h3>
                                  <p class="text-just col-md-11">
                                    <?php echo $notes['product4']['description'];?>  
                                  </p>
                                   
                               <h3 class='h3-span-pro'><?php echo $notes['product5']['title'];?></h3>
                               
                                 <p class="text-just col-md-11">
                                    <?php echo $notes['product5']['description'];?>  
                                 </p>
                                  
                               </div>
                                
                                  <div class="col-md-5 pagination-centered" style="margin-left: 0;">
                                     <img src="<?php echo WEB_PATH;?>/public/front/img/iphone-posmana.png" alt="caisse enregistreuse caltos"  class="col-md-12" style="max-width: 354px;margin-bottom: 1%;height: 525px">
                                     <div class="col-md-2"></div>
                                     <div  class="col-md-8"><h3 class="iphone-view-product">VOIR LA SIMULATION</h3></div>
                                     <div  class="col-md-2" ></div>
                                </div>

                          </div><!-- class="item active row" -->
                           <div class="item   row item-doc1 hieght-pad"></div>
                           <div class="item   row item-doc1 hieght-pad"></div>

                        </div><!-- class="carousel-inner col-md-12" -->
                        

                      </div><!-- class="carousel-inner col-md-12" -->

                    </div><!-- id="tillCarousel" class="carousel slide hidden-phone" data-interval="false" -->
                
            </section>
      </div><!-- id="home-page" class="container content" -->
    </div><!-- id="content" class="container_12" -->
                        
   </div><!-- class="row" -->
</div><!-- class='container' id="giaiphap-ez2" -->
<a href="<?php echo WEB_PATH;?>/front/product/product2">next</a>
      </div>
      <script>
      $('.scroll').jscroll();
      </script>

